var age = 25;
console.log("Is age greater than 18? I predict True.");
console.log(age > 18);
var names = 'Alice';
console.log("Is name equal to 'Alice'? I predict True.");
console.log(names === 'Alice');
var temperature = 28;
console.log("Is temperature less than 0? I predict False.");
console.log(temperature < 0);
var isAdmins = false;
console.log("Is isAdmin equal to true? I predict False.");
console.log(isAdmins === false);
var fruit = 'banana';
console.log("Is fruit not equal to 'apple'? I predict True.");
console.log(fruit !== 'apple');
var distance = 500;
console.log("Is distance equal to 1000? I predict False.");
console.log(distance === 1000);
var isWeekend = true;
console.log("Is it a weekend? I predict True.");
console.log(isWeekend);
var score = 85;
console.log("Is score greater than or equal to 90? I predict False.");
console.log(score >= 90);
var hasPermission = true;
console.log("Does user have permission? I predict True.");
console.log(hasPermission);
var isEven = 7 % 2 === 0;
console.log("Is 7 an even number? I predict False.");
console.log(isEven);
